version: '3'
services:
  myquarkusapp:
    image: myapp
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/mydatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
